koorier/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
    
urlpatterns = [
	path('api/auth/login', obtain_jwt_token, name='api-login'),
    path('api/shippings/', include('shippings.api.urls', namespace='api-shippings')),
    path('', include('shippings.urls', namespace='views-shippings')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shippings/urls.py
from django.urls import path
from shippings.views import ContactView, CheckShippingFormView, HomeView, SendShippingCreateView, CheckShippingStatusListView

app_name = 'shippings-views'
urlpatterns = [
   path('send/', SendShippingCreateView.as_view(), name='send-shipping'),
   path('check-status/', CheckShippingFormView.as_view(), name='check-shipping'),
   path('contact/', ContactView.as_view(), name='contact'),
   path('check-status/<int:code>', CheckShippingStatusListView.as_view(), name='check-shipping-status'),
   path('contact/', ContactView.as_view(), name='contact'),
   path('', HomeView.as_view(), name='home'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
		<div id="page-container">
			<div id="nav">
				<span class="nav-left"><a href="{% url 'views-shippings:home' %}"><div>home</div></a></span>
				<span class="nav-center">
					<span><a href="{% url 'views-shippings:send-shipping' %}"><div>Send shipping</div></a></span>
					<span><a href="{% url 'views-shippings:check-shipping' %}"><div>Check shipping</div></a></span>
					<span><a href="{% url 'views-shippings:contact' %}"><div>Contact</div></a></span>
				</span>
			</div>
			{% if messages %}
				<div class="flash-messages">
					{% for message in messages %}
						<div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
					{% endfor %}
				</div>
			{% endif %}
			{% block main %}
			{% endblock %}
		</div>

		{% block script %}
		{% endblock %}
</body>
</html>